---
title: "dplyr_practice"
output: html_document
---

```{r}
library(plyr)
library(dplyr)

setwd("C:/Users/kjones/Documents/GitHub/codingSupportGroup/dataWrangling/plyr_session") 
setwd("../codingSupportGroup/dataWrangling/plyr_session") 
```

```{r}
##unsophisticated, simplified method to rbind, not practical for combining many files
d01<-read.csv('vst_perindividual_D01.csv')
d02<-read.csv('vst_perindividual_D02.csv')
d03<-read.csv('vst_perindividual_D03.csv')

d03Num<-read.csv('vst_perindividual_D03Number.csv')
d03Order<-read.csv('vst_perindividual_D03Order.csv')

# predict rows in merged dataset
(nrow(d01))+(nrow(d02))+(nrow(d03))

ncol(d01)
ncol(d02)
ncol(d03)

dAll<-rbind(d01, d02, d03)

head(dAll)
tail(dAll)

#check
dim(dAll)

```


```{r}
#Or merge using the plyr method
#better for many files

pathtocsvs<-getwd()

myPrefix<-'vst_perind' 

fileList<-list.files(pathtocsvs)

vstfiles<-fileList[grepl(myPrefix,fileList) | grepl]

# For each file in the list "filelist", read the .csv file to a temporary variable "t", row bind subsequent files to variable "t1", return t1 as final result #Stolen from chuck 5 of cf rmd#
dAll2 = ldply(vstfiles, function(x){
            t <- read.csv(x, header=TRUE, sep=",",stringsAsFactors = FALSE) # read the csv
            t1 <- rbind(t) # rbind it to a temporary object
            return(t1)
}
)

#check it
dim(dAll2)

tail(dAll2)
```


```{r}
#create tbl for futher manipulation - required for dplyr
vst <- tbl_df(dAll)

#take a look
colnames(vst)

#remove dataframe
rm(dAll)

```

#select - for subsetting and ordering columns
```{r}
vstSel<-select(vst, !uid)

#Check it
dim(vstSel)
colnames(vstSel)
str(vstSel)

```

#filter - for subsetting rows
```{r}
vstfil<-filter(vst, pointID <= 30 | (pointID == '41' & plotID=='HARV_043'))
#subset 

dim(vstfil)
head(vstfil)

```

#mutate - create new column with calculation
```{r}
vstmut<-mutate(vst, uid1000=uid*1000, date10=date+10, uid2=uid1000/500)
head(vstmut)

```

#summarize - summarize columns by row values
```{r}
vstSum<-summarize(vst, avg_date=mean(date, na.rm=TRUE), max_date=max(date, na.rm=TRUE), min_date=min(date, na.rm=TRUE ))


```


#rename
```{r}
vst<-rename(vst, chicken = subplotID)

```


#group_by
```{r}
vstGrp<-order_by(vst, subplotID)
```



# %>% pipe


