# returns a domainid value for a given siteID
# vectorize with apply functions e.g. sapply(as.character(input$vector), pasteDomain)
# run the switch()
pasteDomain <- function (x) {
  switch(as.character(x), 
         BART = ,
         HARV = "D01",
         BLAN = ,
         SERC = ,
         SCBI = "D02",
         DSNY = ,
         JERC = ,
         OSBS = "D03",
         GUAN = , 
         LAJA = "D04",
         STEI = ,
         TREE = , 
         UNDE = "D05",
         KONZ = ,
         UKFS = "D06",
         GRSM = ,
         ORNL = ,
         MLBS = "D07",
         DELA = ,
         TALL = ,
         LENO = "D08",
         WOOD = ,
         NOGP = ,
         DCFS = "D09",
         CPER = ,
         STER = "D10",
         OAES = ,
         CLBJ = "D11",
         MOAB = ,
         NIWO = "D13",
         JORN = ,
         SRER = "D14",
         ONAQ = "D15",
         ABBY = "D16",
         SJER = ,
         SOAP = ,
         TEAK = "D17",
         TOOL = ,
         BARR = "D18",
         DEJU = ,
         HEAL = ,
         BONA = "D19")
}